
GET http://localhost:5022

###
GET http://localhost:5022/api/categories

###

GET http://localhost:5022/api/categories?searchValue=Guitar

###

POST http://localhost:5022/api/categories
Content-Type: application/json

{
    "name":"electronics",
    "description": ""
}

###

PUT http://localhost:5022/api/categories/52764bde-f638-489f-b38c-024b569395e0
Content-Type: application/json

{
    "name":"",
    "description":""
}

###

DELETE http://localhost:5022/api/categories/8f666ce7-ac3d-4431-921f-69198870ee7e

###
